# -*- coding: utf-8 -*-
"""结构库浏览页：索引表筛选 + 3D 渲染 + 实时重新打分。"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import streamlit as st

from core.structures import (
    PROJECT_ROOT,
    cif_to_text,
    load_index,
    structure_from_cif,
)
from core.scoring import predict_formation_energy
from core.symmetry import analyze_structure

st.set_page_config(page_title="Structure Library", page_icon="🔬", layout="wide")
st.title("🔬 Structure Library")
st.markdown(
    "Candidates generated by DiffCSP++ (offline GPU pipeline) with cached M3GNet "
    "formation energies and spglib symmetry metadata. Click a row to render."
)


@st.cache_data(show_spinner=False)
def get_index():
    return load_index()


df = get_index()

# ---- 侧栏筛选 ----
with st.sidebar:
    st.markdown("### Filters")
    formulas = st.multiselect(
        "Chemical formula", sorted(df["formula"].unique().tolist()),
        default=sorted(df["formula"].unique().tolist())[:4],
    )
    only_top30 = st.toggle("TOP-30 only (most stable per formula)", value=False)
    only_polar = st.toggle("Polar structures only", value=True)
    max_rows = st.slider("Max rows", 10, 186, 30)

view = df[df["formula"].isin(formulas)] if formulas else df
if only_top30:
    view = view[view["in_top30"] == True]  # noqa: E712
if only_polar:
    view = view[view["is_polar"] == True]  # noqa: E712
view = view.sort_values("eform_eV_per_atom").head(max_rows)

st.caption(f"Showing {len(view)} of {len(df)} structures")

# ---- 索引表 ----
display_cols = ["formula", "eform_eV_per_atom", "spg_symbol", "point_group",
                "is_polar", "n_atoms", "a_A", "b_A", "c_A", "volume_A3",
                "in_top30", "rank", "cif_path"]
event = st.dataframe(
    view[[c for c in display_cols if c in view.columns]],
    use_container_width=True,
    hide_index=True,
    on_select="rerun",
    selection_mode="single-row",
)

selected = event.selection.rows
if selected:
    row = view.iloc[selected[0]]
    cif_path = PROJECT_ROOT / row["cif_path"]

    st.markdown(f"### {row['formula']} — `{row['cif_path'].split('/')[-1]}`")
    m1, m2, m3, m4, m5 = st.columns(5)
    m1.metric("Eform (eV/atom)", f"{row['eform_eV_per_atom']:+.3f}",
              delta="stable" if row["eform_eV_per_atom"] < 0 else "unstable",
              delta_color="normal" if row["eform_eV_per_atom"] < 0 else "inverse")
    m2.metric("Space group", f"{row['spg_symbol']} ({row['spg_number']})")
    m3.metric("Point group", row["point_group"])
    m4.metric("Polar", "Yes ✅" if row["is_polar"] else "No")
    m5.metric("Volume (Å³)", f"{row['volume_A3']:.1f}")

    # ---- 3D 渲染（stmol + py3Dmol，失败降级为 P1 CIF 文本） ----
    left, right = st.columns([3, 2])
    with left:
        try:
            import py3Dmol
            import stmol

            s = structure_from_cif(cif_path)
            view3d = py3Dmol.view(width=620, height=460)
            view3d.addModel(cif_to_text(s), "cif")
            view3d.setStyle({"sphere": {"scale": 0.25}, "stick": {"radius": 0.12}})
            view3d.addUnitCell()
            view3d.zoomTo()
            view3d.setBackgroundColor("white")
            stmol.showmol(view3d, height=460, width=620)
        except Exception as e:
            st.warning(f"3D rendering unavailable ({e.__class__.__name__}); "
                       "showing CIF text instead.")
            st.code(cif_to_text(structure_from_cif(cif_path)), language="text")

    # ---- 实时重新打分 ----
    with right:
        if st.button("🔄 Re-score with M3GNet (live)", use_container_width=True):
            s = structure_from_cif(cif_path)
            with st.spinner("Running M3GNet inference..."):
                eform, method = predict_formation_energy(s)
                sym = analyze_structure(s)
            st.markdown("**Live results**")
            st.markdown(
                f"| quantity | value |\n|---|---|\n"
                f"| eform | **{eform:+.6f} eV/atom** (cached: {row['eform_eV_per_atom']:+.6f}) |\n"
                f"| method | `{method}` |\n"
                f"| space group | {sym['spg_symbol']} ({sym['spg_number']}) |\n"
                f"| point group | {sym['point_group']} |\n"
                f"| polar | {'Yes ✅' if sym['is_polar'] else 'No'} |"
            )
        with st.expander("P1 CIF text (reproducible export)"):
            st.code(cif_to_text(structure_from_cif(cif_path)), language="text")
else:
    st.info("👈 Select a row in the table to render its 3D structure.")
